CREATE DATABASE QLBH

USE QLBH

-- TAO BANG KHACH HANG --
CREATE TABLE KHACHHANG
(
	maKH INT PRIMARY KEY,
	Ten VARCHAR(50),
	Tuoi INT,
	diaChi VARCHAR(30)
)

-- TAO BANG HOA DON --

CREATE TABLE HOADON
(
	maHD INT NOT NULL,
	maKH INT NOT NULL,
	CONSTRAINT FK_HOADON FOREIGN KEY(maKH) REFERENCES KHACHHANG(maKH),
	ngayMua DATETIME,
	tongTien INT
)

ALTER TABLE HOADON
ADD CONSTRAINT PK_HOADON PRIMARY KEY(maHD, maKH)

-- TAO BANG SAN PHAM --
CREATE TABLE SANPHAM
(
	maSP INT PRIMARY KEY,
	tenSP VARCHAR(30),
	gia INT
)

-- TAO BANG CHITIETHOADON --
CREATE TABLE CHITIETHOADON
(
    maHD INT NOT NULL,
    maKH INT NOT NULL,
    maSP INT NOT NULL,
    soLuong INT,
    CONSTRAINT FK1_CHITIETHOADON FOREIGN KEY(maHD, maKH) REFERENCES HOADON(maHD, maKH),
    CONSTRAINT FK2_CHITIETHOADON FOREIGN KEY(maSP) REFERENCES SANPHAM(maSP)
)

ALTER TABLE CHITIETHOADON
ADD CONSTRAINT PK_CHITIETHOADON PRIMARY KEY(maHD, maKH, maSP)